#!/bin/bash
#Function: low-level discovery mounted disk
#Script_name: zabbix_mount_disk_discovery 

mount_disk_discovery()
{
    local regexp="\b(btrfs|ext2|ext3|ext4|jfs|reiser|xfs|ffs|ufs|jfs|jfs2|vxfs|hfs|ntfs|fat32|zfs)\b"
    # 过滤所有已挂载的文件系统
    readarray -t DISK_LIST <<< "$(egrep $regexp /proc/mounts)"
    local num=${#DISK_LIST[@]}
    printf '{\n'
    printf '\t"data":[ '
    for line in "${DISK_LIST[@]}";do
        # 磁盘分区名称
        DEV_NAME=$(echo $line | awk '{print $1}')
        # 文件系统名称，即磁盘分区的挂载点
        FS_NAME=$(echo $line | awk '{print $2}')
        # lsblk命令获取扇区大小，用于计算磁盘读写速率
        DEV_LAST_NAME=$(echo $DEV_NAME | awk -F/ '{print $3}')
        SEC_SIZE=$(lsblk -o NAME,PHY-SEC | grep $DEV_LAST_NAME | awk '{print $2}')
        printf '\n\t\t{'
        printf "\"{#DEV_NAME}\":\"${DEV_NAME}\","
        printf "\"{#FS_NAME}\":\"${FS_NAME}\","
        printf "\"{#SEC_SIZE}\":\"${SEC_SIZE}\"}"
        ((num--))
        [ "$num" == 0 ] && break
        printf ","
    done
    printf '\n\t]\n'
    printf '}\n'
} 
 
case "$1" in
    mount_disk_discovery)
        "$1"
        ;;
    *)
        echo "Bad Parameter."
        echo "Usage: $0 mount_disk_discovery"
        exit 1
        ;;
esac
